
# curl -O https://raw.githubusercontent.com/youwins-lab/KANS/main/MultiCluster-K8S/Vagrantfile

# Base Image
BOX_IMAGE = "ubuntu/focal64"
BOX_VERSION = "20211026.0.0"

# max number of worker nodes
N = 1

Vagrant.configure("2") do |config|
#-----Router Node
    config.vm.define "k8s-rtr" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--groups", "/MultiCuster-Lab"]
        v.name = "MultiCluster-k8s-rtr"
        v.memory = 512
        v.cpus = 1
        v.linked_clone = true
      end
      subconfig.vm.hostname = "k8s-rtr"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "private_network", ip: "192.168.10.254"
      subconfig.vm.network "private_network", ip: "192.168.20.254"
      subconfig.vm.network "forwarded_port", guest: 22, host: 50000, auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/youwins-lab/KANS/main/Multi-Cluster/linux_router.sh" 
    end

#-----Cluster1 Master Node
    config.vm.define "k8s-c1-m" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--groups", "/MultiCuster-Lab"]
        v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        v.name = "MultiCluster-k8s-c1-m"
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
      end
      subconfig.vm.hostname = "k8s-c1-m"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "private_network", ip: "192.168.10.10"
      subconfig.vm.network "forwarded_port", guest: 22, host: 50010, auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/youwins-lab/KANS/main/Multi-Cluster/init_cfg.sh", args: N
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/youwins-lab/KANS/main/Multi-Cluster/c1-route.sh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/youwins-lab/KANS/main/Multi-Cluster/c1-master.sh"
    end

#-----Cluster1 Worker Node
  (1..N).each do |i|
    config.vm.define "k8s-c1-w#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--groups", "/MultiCuster-Lab"]
        v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        v.name = "MultiCluster-k8s-c1-w#{i}"
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
      end
      subconfig.vm.hostname = "k8s-c1-w0"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "private_network", ip: "192.168.10.10#{i}"
      subconfig.vm.network "forwarded_port", guest: 22, host: "5001#{i}", auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/youwins-lab/KANS/main/Multi-Cluster/init_cfg.sh", args: N
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/youwins-lab/KANS/main/Multi-Cluster/c1-route.sh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/youwins-lab/KANS/main/Multi-Cluster/c1-worker.sh"
    end
  end

#-----Cluster2 Master Node
    config.vm.define "k8s-c2-m" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--groups", "/MultiCuster-Lab"]
        v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        v.name = "MultiCluster-k8s-c2-m"
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
      end
      subconfig.vm.hostname = "k8s-c2-m"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "private_network", ip: "192.168.20.10"
      subconfig.vm.network "forwarded_port", guest: 22, host: 50020, auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/youwins-lab/KANS/main/Multi-Cluster/init_cfg.sh", args: N
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/youwins-lab/KANS/main/Multi-Cluster/c2-route.sh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/youwins-lab/KANS/main/Multi-Cluster/c2-master.sh"
    end

#-----Cluster2 Worker Node
  (1..N).each do |i|
    config.vm.define "k8s-c2-w#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--groups", "/MultiCuster-Lab"]
        v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        v.name = "MultiCluster-k8s-c2-w#{i}"
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
      end
      subconfig.vm.hostname = "k8s-c2-w#{i}"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "private_network", ip: "192.168.20.10#{i}"
      subconfig.vm.network "forwarded_port", guest: 22, host: "5002#{i}", auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/youwins-lab/KANS/main/Multi-Cluster/init_cfg.sh", args: N
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/youwins-lab/KANS/main/Multi-Cluster/c2-route.sh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/youwins-lab/KANS/main/Multi-Cluster/c2-worker.sh"
    end
  end

end